return {
    -- {
    --   "antosha417/nvim-lsp-file-operations",
    --   dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "nvim-neo-tree/neo-tree.nvim",
    --   },
    --   config = function()
    --     require("lsp-file-operations").setup()
    --   end,
    -- },
    -- {
    --   "nvim-neo-tree/neo-tree.nvim",
    --   branch = "v3.x",
    --   dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
    --     "MunifTanjim/nui.nvim",
    --     -- {"3rd/image.nvim", opts = {}}, -- Optional image support in preview window: See `# Preview Mode` for more information
    --   },
    --   lazy = false, -- neo-tree will lazily load itself
    --   config = function(_, opts)
    --     -- This is where you can configure Neo-tree
    --     -- You can also do it in the opts table above
    --     require("neo-tree").setup({
    --       source_selector = {
    --         winbar = true,
    --         statusline = false
    --       }
    --     })

    --     -- Keymaps for Neo-tree
    --     vim.keymap.set("n", "<leader>e", "<cmd>Neotree toggle<cr>", { desc = "Toggle Neo-tree" })
    --     vim.keymap.set("n", "<leader>f", "<cmd>Neotree focus<cr>", { desc = "Focus Neo-tree" })
    --   end,
    -- }
  }