[env]
TERM = "xterm-256color"

[window]
padding = {x = 10, y = 10}
decorations = "Buttonless"
opacity = 0.95
blur = true

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic ={ family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[cursor]
style = { shape = "Underline", blinking = "On"}
blink_interval = 500

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]